name: main-workflow
on:
  push:
    branches:
      - master

jobs:
  Hello:
    runs-on: ubuntu-18.04
    steps:
      - name: test
        run: go test -v -race -timeout 30s ./...
      - name: build
        run: go build -v ./cmd/kiddy-line-processor